# Generated by Django 6.0.5 on 2026-05-28 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('plugin_type', models.CharField(max_length=50)),
                ('plugin_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('ERROR', 'Error')], default='STOPPED', max_length=20)),
                ('container_id', models.CharField(blank=True, max_length=128)),
                ('station_lat', models.FloatField(default=0.0)),
                ('station_lon', models.FloatField(default=0.0)),
                ('station_alt', models.FloatField(default=0.0)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Plugin-specific parameters as JSON (e.g. {"file_path": "/data/coords.txt", "coord_type": "ECEF", "coord_format": "GEO"}).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
