# Generated by Django 6.0.8 on 2026-09-19 16:01

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField(blank=True)),
                ('message_type', models.CharField(max_length=32)),
                ('payload_format', models.TextField(default='json')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('message_id', models.TextField(blank=True, null=True, unique=True)),
                ('source_topic', models.TextField(blank=True)),
                ('ingest_topic', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='server_core.plugininstance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plugin', 'message_type', '-created_at'], name='server_core_plugin__8d7ec4_idx'), models.Index(fields=['device', '-created_at'], name='server_core_device_ebaf66_idx')],
            },
        ),
    ]
