# Generated by Django 6.0.8 on 2026-09-19 18:39

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_core', '0002_plugindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{12}$', 'Twelve lowercase hex digits: the MAC of the station interface.')])),
                ('name', models.CharField(blank=True, max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_state_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='RotorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('board_time', models.DateTimeField(blank=True, null=True)),
                ('clock_synced', models.BooleanField(default=False)),
                ('mode', models.CharField(blank=True, max_length=16)),
                ('az_cdeg', models.IntegerField(blank=True, null=True)),
                ('el_cdeg', models.IntegerField(blank=True, null=True)),
                ('pan_mode', models.CharField(blank=True, max_length=16)),
                ('batch_accepted', models.BooleanField(blank=True, null=True)),
                ('batch_error', models.CharField(blank=True, max_length=32)),
                ('latency_ms', models.BigIntegerField(blank=True, null=True)),
                ('rejected_total', models.PositiveBigIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('rotor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='server_core.rotor')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['rotor', '-received_at'], name='server_core_rotor_i_c2296d_idx')],
            },
        ),
    ]
