# Generated by Django 6.0.8 on 2026-09-22 20:52

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_core', '0003_rotor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='rotor',
            field=models.ForeignKey(blank=True, help_text='The rotor this instance drives while RUNNING. Only one running instance per rotor (RF-31.1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_instances', to='server_core.rotor'),
        ),
        migrations.AddField(
            model_name='rotor',
            name='max_azimuth_deg',
            field=models.FloatField(blank=True, help_text='End of the allowed azimuth window. A value below the start wraps through north, e.g. 300 to 60.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)]),
        ),
        migrations.AddField(
            model_name='rotor',
            name='min_azimuth_deg',
            field=models.FloatField(blank=True, help_text='Start of the allowed azimuth window. Leave both azimuth fields empty for no restriction.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)]),
        ),
        migrations.AddField(
            model_name='rotor',
            name='min_elevation_deg',
            field=models.FloatField(default=10.0, help_text='Below this elevation the dispatcher cuts the trajectory and sends HOLD (RF-30.2).', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BATCH', 'Batch'), ('HOLD', 'Hold')], max_length=8)),
                ('t0_ms', models.BigIntegerField()),
                ('t_sent_ms', models.BigIntegerField()),
                ('t_end_ms', models.BigIntegerField()),
                ('points', models.JSONField(default=list)),
                ('reason', models.CharField(blank=True, choices=[('end', 'Trajectory ended'), ('limits', 'Left the rotor limits'), ('expired', 'Every point had already expired')], max_length=16)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='server_core.plugininstance')),
                ('rotor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='server_core.rotor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rotor', '-created_at'], name='server_core_rotor_i_e1cd7b_idx')],
            },
        ),
    ]
