# Generated by Django 6.0 on 2026-10-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_core', '0004_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Plugin-specific parameters as JSON (e.g. {"coord_type": "ECEF", "coord_format": "GEO"}).'),
        ),
    ]
